task: text_regression
base_model: google-bert/bert-base-uncased
project_name: autotrain-bert-sms-spam-finetuned
log: tensorboard
backend: local-cli

data:
  path: sms_spam
  train_split: train
  valid_split: null
  column_mapping:
    text_column: sms
    target_column: label

params:
  max_seq_length: 512
  epochs: 3
  batch_size: 4
  lr: 2e-5
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 1
  mixed_precision: fp16

hub:
  username: ${HF_USERNAME}
  token: ${HF_TOKEN}
  push_to_hub: true