name: Feature Request
description: 🚀 Submit a proposal/request for a new AutoTrain feature
title: ""
labels: ["feature request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a feature request! Please provide as much detail as possible.

  - type: textarea
    id: feature-request
    attributes:
      label: Feature Request
      description: A clear and concise description of the feature proposal. Please provide a link to the paper and code if they exist.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, details, or screenshots about the feature request here.
    validations:
      required: false
