#!/usr/bin/env python3
import argparse

from autonlp import AutoNLP


def parse_args():
    parser = argparse.ArgumentParser("AutoNLP")
    parser.add_argument("--org", required=True, type=str, help="Organization name")
    parser.add_argument("--user", required=True, type=str, help="Username")
    parser.add_argument("--org", required=True, type=str, help="Organization name")
    return parser.parse_args()