name: Delete doc comment

on:
  workflow_run:
    workflows: ["Delete doc comment trigger"]
    types:
      - completed

jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment.yml@17ccdf17e0f5e5f88b1ce9f20b3b73fb19017169  # main
    secrets:
      comment_bot_token: ${{ secrets.COMMENT_BOT_TOKEN }}