name: Docker Hub

on:
  push:
    branches:
      - main

jobs:
  dockerhub:
    name: Docker Hub
    runs-on:
      group: 'aws-general-8-plus'
    steps:
      - name: Check out the repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349  # v3.7.1

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567  # v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set short git commit SHA
        id: vars
        run: |
          sha=$(git rev-parse --short ${{ github.sha }})
          echo "SHA=$sha" >> $GITHUB_ENV

      - name: SHA
        run: echo ${{ env.SHA }}

      - name: Build and Push Docker Image
        run: |
          docker build -t autotrain-advanced:latest .
          docker tag autotrain-advanced:latest huggingface/autotrain-advanced:latest
          docker tag autotrain-advanced:latest huggingface/autotrain-advanced:${{ env.SHA }}
          docker push huggingface/autotrain-advanced:latest
          docker push huggingface/autotrain-advanced:${{ env.SHA }}